server: 
  port: 8185
  
#spring
spring:
  application:    name: ehr-consumer
  #cloud:   # consul:    #  host: 127.0.0.1
     # port: 8500
      #discovery:
       # service-name: ${spring.application.name}  #注册到consul的服务名称
  boot:    admin:      client:        url:        - "http://192.168.1.131:8100"
  #zipkin
  zipkin:    base-url: http://192.168.1.131:9411
  sleuth:    sampler:      probability: 1  #样本采集量，默认为0.1
  
  datasource:
    name : druidDataSource
    type : com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.130:3308/ehr_admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: roye
      password: 123456
      filters: stat,wall,log4j,config  #配置监控统计拦截的filters,去掉后监控界面sql无法进行统计，wall用于防火墙
      max-active: 100  #最大连接数
      initial-size: 1  #初始化大小
      max-wait: 60000  #获取连接等待超时时间
      min-idle: 1      #最小连接数
      time-between-eviction-runs-millis: 60000  #间隔多久才进行一次检测，检查需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000    #一个连接在池中最小生存的时间，单位是毫秒
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      # 是否启用StatFilter默认值true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-cookie-name: admin
        principal-session-name: admin
        profile-enable: true
      stat-view-servlet:
        url-pattern: /druid/*  # 监控页面访问路径
        # 允许清空统计数据
        reset-enable: true
        login-username: roye
        login-password: 123456
        # StatViewSerlvet展示出来的监控信息比较敏感，是系统运行的内部情况，如果你需要做访问控制，可以配置allow和deny这两个参数
        # deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。如果allow没有配置或者为空，则允许所有访问
        # 配置的格式
          # <IP>
          # 或者<IP>/<SUB_NET_MASK_size>其中128.242.127.1/24
          # 24表示，前面24位是子网掩码，比对的时候，前面24位相同就匹配,不支持IPV6。
        allow:
        deny:

#开放健康检查接口
management:  endpoints:    web:      exposure:        include:        - "*"
  endpoint:    health:      show-details: ALWAYS
      
#ribbon 负载均衡策略配置 随机策略
ehr-producer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    
#断熔器
feign:  hystrix:    enabled: true