server:
  port: 8503
spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}  #注册到consul的服务名称
      # 健康检查 一定要配置 结合 spring-boot-starter-actuator 使用
        health-check-path: /actuator/health
        health-check-interval: 10s
    #网关配置
    gateway:
      filter:
        remove-non-proxy-headers:
          headers:
          - dummy
      discovery:
        locator:
          enabled: true  #从注册中心发现，不用每个路由都配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

