server:
  port: 8100
spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}  #注册到consul的服务名称
      # 健康检查 一定要配置 结合 spring-boot-starter-actuator 使用
        health-check-path: /actuator/health
        health-check-interval: 10s
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

    